version: "2"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - web-variables.env
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
